In [35]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [47]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [36]:
df = pd.read_csv("../data/StudentsPerformance.csv")

EDA

In [37]:
df.shape


df.dtypes
#df.describe()
df.isnull().sum()

#df.info()
df.head(10)
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [67]:
df_cleaned = df.drop(['reading score','writing score'],axis = 1)
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [39]:

y = df_cleaned['math score']
X = df_cleaned.drop(['math score'], axis = 1)

In [40]:
print(y.shape)
print(X.shape)

(1000,)
(1000, 5)

Applying one hot encoding for the categorical data

In [41]:
X = pd.get_dummies(X,drop_first = True)

In [ ]:
X.shape

(1000, 12)

In [68]:
X.head()

,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school,lunch_standard,test preparation course_none
0,False,True,False,False,False,True,False,False,False,False,True,True
1,False,False,True,False,False,False,False,False,True,False,True,False
2,False,True,False,False,False,False,False,True,False,False,True,True
3,True,False,False,False,False,False,False,False,False,False,False,True
4,True,False,True,False,False,False,False,False,True,False,True,True

In [ ]:
X.info()

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [52]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

error = mean_absolute_error(y_test, y_pred)
print(error)

11.269872775277623

In [69]:
import pickle as pkl
with open('../models/model.pkl', 'wb') as f:
    pkl.dump(model, f)

with open('../models/X_columns.pkl', 'wb') as f:
    pkl.dump(X.columns, f)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
model_2 = DecisionTreeRegressor(random_state = 42, max_depth = 5)
model_2.fit(X_train,y_train)
y_pred = model_2.predict(X_test)
error2 = mean_absolute_error(y_test,y_pred)
print(error2)

11.871321302400808

In [63]:
from sklearn.linear_model import Ridge
model_3 = Ridge(alpha = 1.0)
model_3.fit(X_train, y_train)
y_pred = model_3.predict(X_test)
error3 = mean_absolute_error(y_test, y_pred)
print(error3)

11.278073062180235